### ISSUE TITLE
services.sh bug (iptables)

### ISSUE THREAD

**Issue by pmsullivan85** [RedHatGov/stig-fix-el6#36]
I recently started using the stig-fix RPM to harden our deployed systems.
I noticed after scanning that iptables was disabled, and tracked it down to:

misc/services.sh script actually disables the iptables service.

The stanza which is attempting to handle the ip6tables uses  $SRV without initializing it, so it ends up acting on 'iptables' instead of the intended 'ip6tables'. (so it is disabled if ipv6 isn't active)

**Comment by fcaviggia** [comment]
Fixed. Great catch!
