### ISSUE TITLE
toggle_udf.sh typo

### ISSUE THREAD

**Issue by pmsullivan85** [RedHatGov/stig-fix-el6#38]
Line 43 of toggle_udf.sh -

typo - 'flase' should be 'false'

change:   sed -i '/^install udf \/bin\/false/ c\#install udf \/bin\/flase' $BLACKLIST
to:            sed -i '/^install udf \/bin\/false/ c\#install udf \/bin\/false' $BLACKLIST

**Comment by fcaviggia** [comment]
Fixed. Rolling new RPM here shortly. Thanks for catching all these bugs.
